### ISSUE TITLE
Does not work with nodejs?

### ISSUE THREAD

**Issue by dnz-bdeboer** [badgateway/fetch-mw-oauth2#56]
It seems this project doesn't work with plain node is it?

I get errors like this:

```
./node_modules/fetch-mw-oauth2/src/fetch-wrapper.ts:66
    const request = new Request(input, init);
                    ^
ReferenceError: Request is not defined
```

**Comment by evert** [comment]
Hi @dnz-bdeboer ,

Version 2 of this library is currently under development. It should work swimmingly on Node 18, where fetch/Request/Response are now built in.

For Node versions under 18, you'll need to polyfill the library using `node-fetch`. There's some instructions on this page on how to do this: https://www.npmjs.com/package/node-fetch#loading-and-configuring-the-module

The goal is to have these instructions also on the `fetch-mw-oauth2` readme, but this hasn't been completed yet.

**Comment by evert** [comment]
Hi @dnz-bdeboer ,

Try installing the latest alpha. This has better support for older Node versions:

    npm i fetch-mw-oauth2@alpha

If you are running Node 16 or 14, you do still need polyfills but these steps have now been documented on the readme:

https://github.com/badgateway/fetch-mw-oauth2#support-for-older-node-versions

**Comment by evert** [comment]
I forgot to ask, but.. if you are using v1 of this library and you're getting those errors, then the same polyfills should also work!

**Comment by anentropic** [comment]
I am getting this error on Node 16 in a Typescript project

I have:
```
"@badgateway/oauth2-client": "^2.0.17",
"node-fetch@2": "^2.6.0",
```

when I step through to reach the error in vscode debugger I arrive at `fetch-wrapper.js`:

```js
        const request = new Request(input, init);
```

it seems like the problem is the code expects `Request` object to exist, but in Node 16 it doesn't. Presumably node-fetch is supposed to provide it auto-magically?

I can see the node-fetch 3.x docs https://www.npmjs.com/package/node-fetch#installation says that I need to create a polyfill file and import that first.

The node-fetch 2.6.7 docs don't have any such detail though.

If I try to create it anyway I get errors like:
```
    src/fetch-polyfill.ts:11:3 - error TS2322: Type 'typeof Response' is not assignable to type '{ new (body?: BodyInit | null | undefined, init?: ResponseInit | undefined): Response; prototype: Response; error(): Response; redirect(url: string | URL, status?: number | undefined): Response; }'.
      Types of property 'prototype' are incompatible.
        Property 'formData' is missing in type 'import("/Users/paul/Documents/Dev/Work/bulb/ev-charging/api/node_modules/@types/node-fetch/index").Response' but required in type 'Response'.
```

**Comment by anentropic** [comment]
never mind, just read properly the instructions at https://github.com/badgateway/oauth2-client#support-for-older-node-versions and used the polyfill given there instead 👍
